READ_ONLY_CODING_GRAPH = "solo-readonly"
READ_ONLY_CODING_VERSION = 1

MODIFYING_CODING_GRAPH = "solo-modifying"
MODIFYING_CODING_VERSION = 1

TEAM_CODING_GRAPH = "team-coding"
TEAM_CODING_VERSION = 2
SCOPED_TEAM_CODING_VERSION = 1

TEAM_ROLE_GRAPH = "team-role"
TEAM_ROLE_VERSION = 1

TEAM_VERIFIER_GRAPH = "team-verifier"
TEAM_VERIFIER_VERSION = 1

RUNTIME_PROBE_GRAPH = "runtime-probe"
RUNTIME_PROBE_VERSION = 1
